name: app1

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  DOCKERHUB_NAMESPACE: jkosik
  DOCKERHUB_REPO: app1

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Generate Image tag
        run: |
          export TAG=dev-`date +%s`
          echo "::set-env name=TAG::$TAG"

      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.DOCKERHUB_REPO }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_file: Dockerfile
          tag: $TAG
