name: app1

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  DOCKERHUB_NAMESPACE: jkosik
  DOCKERHUB_REPO: app1

on:
  push:
    branches:
      - 'dev'
      - 'stage'
      - 'main'

  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Generate Image tag for DEV
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "TAG=dev-`date +%s`" >> $GITHUB_ENV
          echo "Building Image Tag ${{ env.TAG }}"

      - name: Generate Image tag for STAGE
        if: github.ref == 'refs/heads/stage'
        run: |
          echo "TAG=stage-`date +%s`" >> $GITHUB_ENV
          echo "Building Image Tag ${{ env.TAG }}"

      - name: Generate Image tag for MAIN
        if: github.ref == 'refs/heads/main'
        run: |
          echo "TAG=`date +%s`" >> $GITHUB_ENV
          echo "Building Image Tag ${{ env.TAG }}"

      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.DOCKERHUB_REPO }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_file: Dockerfile
          tag: ${{ env.TAG }}
